apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: challenge-app
  name: app
  namespace: infra-challenge
spec:
  selector:
    matchLabels:
      app: challenge-app
  template:
    metadata:
      labels:
        app: challenge-app
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: app-configs
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: app-configs
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: DB_DATABASE
              name: app-secrets
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: app-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: app-secrets
        image: cesarbgoncalves/infra-challenge:1.0.0
        imagePullPolicy: IfNotPresent
        name: challenge
        ports:
        - containerPort: 8000
          name: http-api
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
